import type { RentvineExport } from "../raw";

// Bundled Rentvine snapshot for the "pmilighthouse" account, pulled via the
// Rentvine connector. Raw source data; the transform maps it to canonical and
// the generic loader writes it. When the live API client is wired up, this file
// is replaced by a live extract() call — transform + loader stay the same.
//
// Coverage: all 46 properties (owner/portfolio), active leases (tenant + contact
// + term + rent + balances), and the full work-order history. Work orders on
// properties no longer managed are skipped by the loader.

export const pmilighthouse: RentvineExport = {
  account: "pmilighthouse",
  properties: [
    { id: 5, street: "18 Timber Ridge Drive", city: "Holtsville", state: "NY", zip: "11742", type: "Single Family Home", portfolioId: 6, owner: "Jennifer Seeba" },
    { id: 6, street: "37 Andiron Lane", city: "Brookhaven", state: "NY", zip: "11719", type: "Single Family Home", portfolioId: 7, owner: "Anne Arnett & Chad Arnett" },
    { id: 9, street: "11 Glen Hollow Drive", city: "Holtsville", state: "NY", zip: "11742", type: "Single Family Home", portfolioId: 9, owner: "Matthew Minkoff" },
    { id: 11, street: "5 Ring Ln", city: "Levittown", state: "NY", zip: "11756", type: "Single Family Home", portfolioId: 11, owner: "Neil Maclean" },
    { id: 18, street: "29 Parkway Avenue", city: "Amityville", state: "NY", zip: "11701", type: "Single Family Home", portfolioId: 16, owner: "Faye McCullough-Simpson" },
    { id: 19, street: "71 Lambeth Street", city: "Holbrook", state: "NY", zip: "11741", type: "Single Family Home", portfolioId: 17, owner: "Latif Legacy Holdings" },
    { id: 20, street: "21 Cleveland st apt 1", city: "Valley Stream", state: "NY", zip: "11580", type: "Apartment", portfolioId: 18, owner: "Khan and Kabir Irrevocable Family Trust" },
    { id: 23, street: "11 Grassfield Road", city: "Great Neck", state: "NY", zip: "11024", type: "Single Family Home", portfolioId: 21, owner: "Ross Freeman", groups: ["Squatterwatch Properties"] },
    { id: 24, street: "1 Thornton St", city: "Patchogue", state: "NY", zip: "11772", type: "Single Family Home", portfolioId: 22, owner: "Scott Kanter" },
    { id: 27, street: "161 Smithtown Polk Blvd", city: "Centereach", state: "NY", zip: "11720", type: "Single Family Home", portfolioId: 25, owner: "Yomaris Macdonald" },
    { id: 30, street: "257 Center St", city: "Williston Park", state: "NY", zip: "11596", type: "Single Family Home", portfolioId: 29, owner: "MAC SALIB, LLC" },
    { id: 35, street: "185 North Indiana Avenue", city: "Lindenhurst", state: "NY", zip: "11757", type: "Apartment", portfolioId: 32, owner: "Richard Lahn" },
    { id: 36, street: "19 Colgate Road", city: "Great Neck", state: "NY", zip: "11023", type: "Single Family Home", portfolioId: 34, owner: "Ila Mishra & Amogh Mahapatra" },
    { id: 37, street: "25 Thorney Avenue", city: "Huntington Station", state: "NY", zip: "11746", type: "Single Family Home", portfolioId: 35, owner: "Epifanio Vasquez" },
    { id: 38, street: "144 Storm Drive", city: "Holtsville", state: "NY", zip: "11742", type: "Single Family Home", portfolioId: 36, owner: "Daniel Patti" },
    { id: 40, street: "66 Francis Court", city: "Elmont", state: "NY", zip: "11003", type: "Single Family Home", portfolioId: 38, owner: "Gilma Escobar" },
    { id: 41, street: "24-12 42nd Road Apt 2E", city: "Long Island City", state: "NY", zip: "11101", type: "Condo", portfolioId: 39, owner: "Dana Cho" },
    { id: 44, street: "160 Red Dirt Rd", city: "East Hampton", state: "NY", zip: "11937", type: "Single Family Home", portfolioId: 42, owner: "Kevin Kunkel", groups: ["Squatterwatch Properties"] },
    { id: 45, street: "25 Willow Drive", city: "Coram", state: "NY", zip: "11727", type: "Townhouse", portfolioId: 43, owner: "Joseph Mccabe" },
    { id: 48, street: "8204 138th Street", city: "Jamaica", state: "NY", zip: "11435", type: "Apartment", portfolioId: 45, owner: "Patricia Robbins" },
    { id: 49, street: "130 Rolling Street", city: "Lynbrook", state: "NY", zip: "11563", type: "Single Family Home", portfolioId: 46, owner: "Sanae Smili" },
    { id: 50, street: "17 Rondell Ln", city: "Centereach", state: "NY", zip: "11720", type: "Single Family Home", portfolioId: 47, owner: "Catherine Wang" },
    { id: 51, street: "15 Canyon Street", city: "Huntington", state: "NY", zip: "11743", type: "Single Family Home", portfolioId: 48, owner: "15 Canyon Street LLC" },
    { id: 52, street: "64 Blacksmith Rd", city: "Levittown", state: "NY", zip: "11756", type: "Single Family Home", portfolioId: 49, owner: "Russell Heim & Ana Heim" },
    { id: 53, street: "2 Carlyle Drive", city: "Glen Cove", state: "NY", zip: "11542", type: "Single Family Home", portfolioId: 50, owner: "Yi Liu" },
    { id: 55, street: "128 Lockwood Avenue", city: "Huntington Station", state: "NY", zip: "11746", type: "Single Family Home", portfolioId: 52, owner: "Brown Family Irrevocable Trust (128 Lockwood Ave)" },
    { id: 56, street: "117 Upton Dr", city: "Sound Beach", state: "NY", zip: "11789", type: "Single Family Home", portfolioId: 53, owner: "Fabliha Anbar" },
    { id: 57, street: "136 West Henrietta Avenue", city: "Oceanside", state: "NY", zip: "11572", type: "Single Family Home", portfolioId: 54, owner: "Michael Haskel" },
    { id: 58, street: "115 8th Avenue", city: "Huntington Station", state: "NY", zip: "11746", type: "Single Family Home", portfolioId: 57, owner: "Brown Family Irrevocable Trust (115 8th Ave.)" },
    { id: 61, street: "4072 Darby Lane", city: "Seaford", state: "NY", zip: "11783", type: "Single Family Home", portfolioId: 58, owner: "Marcie Jacob", groups: ["Squatterwatch Properties"] },
    { id: 62, street: "356 Vanderbilt Motor Parkway", city: "Hauppauge", state: "NY", zip: "11788", type: "Commercial", portfolioId: 59, owner: "Taku Aoki", groups: ["Squatterwatch Properties"] },
    { id: 63, street: "61 Mill Lane", city: "Huntington", state: "NY", zip: "11743", type: "Single Family Home", portfolioId: 60, owner: "Gail Lodge", groups: ["Squatterwatch Properties"] },
    { id: 67, street: "37 Margaret Blvd", city: "Merrick", state: "NY", zip: "11566", type: "Single Family Home", portfolioId: 61, owner: "37 Margaret Blvd LLC" },
    { id: 68, street: "54 Pembrook Drive", city: "Stony Brook", state: "NY", zip: "11790", type: "Single Family Home", portfolioId: 64, owner: "Liza Micheva" },
    { id: 69, street: "2077 Feuereisen Ave", city: "Ronkonkoma", state: "NY", zip: "11779", type: "Single Family Home", portfolioId: 65, owner: "Lauren Weiss" },
    { id: 70, street: "6 Harbor Ln", city: "Glen Head", state: "NY", zip: "11545", type: "Single Family Home", portfolioId: 66, owner: "Katerina Stella" },
    { id: 71, street: "654 Bermuda Rd", city: "West Babylon", state: "NY", zip: "11704", type: "Single Family Home", portfolioId: 67, owner: "Vishnu Haldar" },
    { id: 72, street: "100 West Broadway Apt 4E", city: "Long Beach", state: "NY", zip: "11561", type: "Single Family Home", portfolioId: 68, owner: "Kara Rozansky" },
    { id: 73, street: "47 Columbine Ave", city: "Islip", state: "NY", zip: "11751", type: "Single Family Home", portfolioId: 69, owner: "Scott Gesele" },
    { id: 74, street: "16 Bittersweet Place", city: "Huntington", state: "NY", zip: "11743", type: "Single Family Home", portfolioId: 70, owner: "Ed Fleiss" },
    { id: 75, street: "18-47 26th Rd", city: "Astoria", state: "NY", zip: "11102", type: "Single Family Home", portfolioId: 54, owner: "Michael Haskel" },
    { id: 76, street: "15 Amys Court", city: "East Hampton", state: "NY", zip: "11937", type: "Multiplex", portfolioId: 63, owner: "Joyce Hulsebos" },
    { id: 77, street: "13 Beaver Trail", city: "Coram", state: "NY", zip: "11727", type: "Single Family Home", portfolioId: 71, owner: "Christian Chike" },
    { id: 78, street: "1245 U.S. 1", city: "Edison", state: "NJ", zip: "08837", type: "Commercial", portfolioId: 72, owner: "GE Office rentals llc" },
    { id: 79, street: "796 Amboy Avenue", city: "Perth Amboy", state: "NJ", zip: "08861", type: "Commercial", portfolioId: 72, owner: "GE Office rentals llc" },
    { id: 81, street: "796 Amboy Avenue", city: "Perth Amboy", state: "NJ", zip: "08861", type: "Commercial", portfolioId: 72, owner: "GE Office rentals llc" },
  ],
  activeLeases: [
    { prop: 30, leaseId: 19, tenant: "Taichna Charles", email: "c.taichna@yahoo.com", phone: "+15164767445", start: "2026-10-01", end: "2028-09-30", rent: 5700, balanceDue: 865.95 },
    { prop: 71, leaseId: 49, tenant: "Nebia Chui", email: "knsj8163@aol.com", phone: "+16315074202", start: "2026-10-01", end: "2028-03-31", rent: 4500 },
    { prop: 37, leaseId: 47, tenant: "Miljiam Licona", email: "miljiamivonnelicona28@gmail.com", phone: "+19342069533", start: "2026-08-15", end: "2027-08-31", rent: 4800 },
    { prop: 67, leaseId: 48, tenant: "Audrey Rakovich Seville", email: "audreyseville@protonmail.com", phone: "+19178389520", start: "2026-08-15", end: "2028-08-31", rent: 5625 },
    { prop: 35, leaseId: 21, tenant: "Megan Purdue", email: "parduemegan@yahoo.com", phone: "+16316127931", start: "2026-08-01", end: "2027-07-31", rent: 3000, depositBalance: 2800 },
    { prop: 20, leaseId: 14, tenant: "Victoria Pierre-Louis", email: "victoria.pierrelouis@yahoo.com", phone: "+17185933557", start: "2026-07-01", end: "2028-06-30", rent: 2800 },
    { prop: 41, leaseId: 34, tenant: "Selina Sun", email: "selinas.sjy@gmail.com", phone: "+19175813783", start: "2026-07-01", end: "2027-09-30", rent: 5200, depositBalance: 5200 },
    { prop: 49, leaseId: 46, tenant: "Lori Stevens", email: "lasny1993@gmail.com", phone: "+15164925070", start: "2026-06-19", end: "2027-06-30", rent: 4900, depositBalance: 1500 },
    { prop: 19, leaseId: 12, tenant: "Karen Vasilecozzo", email: "Mandy02009@gmail.com", phone: "+16317673197", start: "2026-06-01", end: "2028-05-31", rent: 4800 },
    { prop: 48, leaseId: 33, tenant: "Linda Muñoz Gallo", email: "lindavivianamunoz@gmail.com", phone: "+13476471691", start: "2026-06-01", end: "2027-05-31", rent: 2696 },
    { prop: 58, leaseId: 45, tenant: "Marvin Geovanni Raymundo", email: "marvinraymundo2015@gmail.com", phone: "+16319604773", start: "2026-05-01", end: "2027-04-30", rent: 4200 },
    { prop: 56, leaseId: 44, tenant: "Claudia Lipinski", email: "claudia.lipinski64@gmail.com", phone: "+16312207019", start: "2026-04-18", end: "2027-04-30", rent: 2500, depositBalance: 250 },
    { prop: 40, leaseId: 27, tenant: "Pamela Roberts", email: "deroche2002@yahoo.com", phone: "+13478582688", start: "2026-04-01", end: "2027-03-31", rent: 4425, depositBalance: 250 },
    { prop: 53, leaseId: 43, tenant: "Alec Longo", email: "Alongo@opt4lifeinc.com", phone: "+16319439655", start: "2026-03-22", end: "2027-03-31", rent: 6025 },
    { prop: 9, leaseId: 10, tenant: "Catherine Smith", email: "cat42985@gmail.com", phone: "+16315619058", start: "2026-02-01", end: "2027-01-31", rent: 2050 },
    { prop: 11, leaseId: 6, tenant: "julie dimaggio", email: "juliedimaggio1@outlook.com", phone: "+15163531279", start: "2026-01-15", end: "2027-01-14", rent: 4100 },
    { prop: 48, leaseId: 28, tenant: "Hossein Torresramos", email: "housseinaissantorresramos@gmail.com", start: "2026-01-01", end: "2026-12-31", rent: 2325 },
    { prop: 48, leaseId: 31, tenant: "Cynthia Tabora", email: "rcynthiaa21@yahoo.com", phone: "+13476392146", start: "2025-12-01", end: "2026-11-30", rent: 2500 },
    { prop: 55, leaseId: 40, tenant: "Joely Rojas López", email: "j.rojaslopez@hotmail.com", phone: "+16316394073", start: "2025-11-09", end: "2027-11-30", rent: 4000 },
    { prop: 24, leaseId: 13, tenant: "Bobbye Sanders", email: "bobbye_sanders@aol.com", phone: "+19282761601", start: "2025-11-01", end: "2026-10-31", rent: 3200 },
    { prop: 51, leaseId: 38, tenant: "Michael Serrant", email: "Michael.serrant7@gmail.com", phone: "+15168534469", start: "2025-10-01", end: "2027-09-30", rent: 3500, balanceDue: 7875 },
    { prop: 5, leaseId: 4, tenant: "Stephany Seifert", email: "stephanyseifert@gmail.com", phone: "+16316334134", start: "2025-09-01", end: "2027-08-31", rent: 3500 },
    { prop: 27, leaseId: 18, tenant: "Chantel Rausche Williams", email: "Mizzchanshine@yahoo.com", phone: "+16318966721", start: "2025-09-01", end: "2027-08-31", rent: 4300 },
    { prop: 50, leaseId: 37, tenant: "Maria Galindo", email: "m.galindo72@icloud.com", phone: "+15168500848", start: "2025-09-01", end: "2027-08-31", rent: 4500, depositBalance: 250 },
    { prop: 52, leaseId: 35, tenant: "Robert Kreib", email: "Robertkreib1@gmail.com", phone: "+15169030544", start: "2025-08-01", end: "2027-07-31", rent: 4500 },
    { prop: 79, leaseId: 50, tenant: "Rachel Barnes", email: "rbarnes76@gmail.com", phone: "+17373791181", start: "2025-07-01", end: "2026-06-30", rent: 1863, balanceDue: 1913 },
    { prop: 45, leaseId: 30, tenant: "Michael J Hayes", email: "Mikehayes23@aol.com", phone: "+16319223756", start: "2025-06-15", end: "2027-06-14", rent: 4700 },
    { prop: 78, leaseId: 51, tenant: "Health Up Training and Services LLC", email: "Healthuptraining@gmail.com", phone: "+19082674143", start: "2025-05-01", end: "2030-04-30", rent: 3060, balanceDue: 3060 },
    { prop: 36, leaseId: 25, tenant: "Nechama Neren Silverman", email: "Nsilverman0523@gmail.com", start: "2025-02-15", end: "2027-02-28", rent: 7000 },
    { prop: 18, leaseId: 15, tenant: "Timothy Robert Walker", email: "Timothywalker_2@yahoo.com", phone: "+17344976102", start: "2024-07-15", end: "2026-07-31", rent: 4500, balanceDue: 18564.40 },
    { prop: 6, leaseId: 5, tenant: "Jonathan M Ebel", email: "Jebel@netw1.com", phone: "+16313351589", start: "2024-01-01", end: "2026-12-31", rent: 5260 },
  ],
  workOrders: [
    { id: 423, prop: 24, desc: "Refrigerator is not functioning and appears to be completely dead", priority: "normal" },
    { id: 422, prop: 62, desc: "Junk cleanup in parking lot", priority: "normal" },
    { id: 421, prop: 77, desc: "Clean out the trash in the house", priority: "normal" },
    { id: 420, prop: 35, desc: "Buy fly traps", priority: "normal" },
    { id: 419, prop: 71, desc: "Chimney cleaning", priority: "normal" },
    { id: 418, prop: 5, desc: "The garage door won't open because the opener is not working", priority: "normal" },
    { id: 417, prop: 5, desc: "Three outlets are not working", priority: "normal" },
    { id: 416, prop: 69, desc: "Clogged drain line from the AHU causing overflow into the emergency drain pan and water damage.", priority: "normal" },
    { id: 415, prop: 41, desc: "The kitchen sink is leaking", priority: "normal" },
    { id: 414, prop: 67, desc: "Repair of the showerheads and handles", priority: "normal" },
    { id: 413, prop: 48, desc: "Buy a new garbage can as per the new NYC law", priority: "normal" },
    { id: 412, prop: 75, desc: "Buy a new garbage can per the new NYC law.", priority: "normal" },
    { id: 411, prop: 75, desc: "Do the registration of the building for 2027", priority: "normal" },
    { id: 410, prop: 48, desc: "Utility Bill", priority: "normal" },
    { id: 409, prop: 67, desc: "Fire place repair", priority: "normal" },
    { id: 408, prop: 58, desc: "New light outside", priority: "normal" },
    { id: 407, prop: 48, desc: "Check the air conditioning unit - Unit 1 tenant reports loud noise, not cooling well. Related to WO 100271.", priority: "normal" },
    { id: 406, prop: 61, desc: "Lawn mowing", priority: "normal" },
    { id: 405, prop: 61, desc: "Lawn mowing", priority: "normal" },
    { id: 404, prop: 48, desc: "Do the registration of the building for 2027", priority: "normal" },
    { id: 403, prop: 19, desc: "Purchase a new washing machine — repair company recommends replacing; machine too old to repair.", priority: "normal" },
    { id: 402, prop: 36, desc: "AC is not working", priority: "normal" },
    { id: 401, prop: 23, desc: "Shower Curtain", priority: "normal" },
    { id: 400, prop: 19, desc: "The washing machine is not completing the cycle, and the water is staying in it.", priority: "normal" },
    { id: 399, prop: 61, desc: "The siding came off and needs to be repaired", priority: "normal" },
    { id: 398, prop: 49, desc: "Need to send a plumber to repair the hose bib outside", priority: "normal" },
    { id: 397, prop: 75, desc: "Set up utilities in the building; confirm with attorney about the basement door handle.", priority: "normal" },
    { id: 396, prop: 75, desc: "Send registration paperwork to NYC HPD", priority: "normal" },
    { id: 395, prop: 44, desc: "Take pictures for property insurance.", priority: "normal" },
    { id: 394, prop: 44, desc: "The barn door came off and needs to be rehung.", priority: "normal" },
    { id: 393, prop: 37, desc: "Counter top stove: burners are not working", priority: "normal" },
    { id: 392, prop: 48, desc: "AC installation", priority: "normal" },
    { id: 391, prop: 53, desc: "Electric Bill.", priority: "normal" },
    { id: 390, prop: 56, desc: "The electricity keeps tripping in the house", priority: "normal" },
    { id: 389, prop: 52, desc: "Leak in the back porch ceiling", priority: "normal" },
    { id: 388, prop: 35, desc: "Move the AC units to the street.", priority: "normal" },
    { id: 387, prop: 35, desc: "Buy new fly flags", priority: "normal" },
    { id: 386, prop: 52, desc: "Get rid of the old broken dryer & stove", priority: "normal" },
    { id: 385, prop: 52, desc: "Water coming in through the awning ceiling when it rains.", priority: "normal" },
    { id: 384, prop: 5, desc: "2 new bushes", priority: "normal" },
    { id: 383, prop: 37, desc: "Work Order created in LeadSimple with empty description", priority: "low" },
    { id: 382, prop: 62, desc: "Install signage for the fire department at the restaurant.", priority: "normal" },
    { id: 381, prop: 62, desc: "Cut the lawn", priority: "normal" },
    { id: 380, prop: 69, desc: "Get a quote and do the sealcoating on the driveway.", priority: "normal" },
    { id: 379, prop: 69, desc: "Install a light in the kitchen", priority: "normal" },
    { id: 378, prop: 30, desc: "The fridge is not working", priority: "normal" },
    { id: 377, prop: 5, desc: "Replace 2 small bushes.", priority: "normal" },
    { id: 376, prop: 19, desc: "Leak in the ceiling by the living room.", priority: "normal" },
    { id: 375, prop: 19, desc: "Leak from the bathtub.", priority: "normal" },
    { id: 374, prop: 62, desc: "Repair of the alarm for the fire suppression system.", priority: "normal" },
    { id: 373, prop: 23, desc: "Finish up the work on the outlet covers", priority: "normal" },
    { id: 372, prop: 19, desc: "The sliding door is leaking again", priority: "normal" },
    { id: 371, prop: 48, desc: "Water Bill", priority: "normal" },
    { id: 370, prop: 61, desc: "Close the window", priority: "normal" },
    { id: 369, prop: 68, desc: "Gutter Cleaning", priority: "normal" },
    { id: 368, prop: 6, desc: "The washing machine needs replacing (mold in the drum).", priority: "normal" },
    { id: 367, prop: 6, desc: "The dryer plug is giving off a burning smell", priority: "normal" },
    { id: 366, prop: 11, desc: "Tree in the front yard broke and fell; no injuries or damage.", priority: "normal" },
    { id: 365, prop: 20, desc: "Light in the den is not working", priority: "normal" },
    { id: 364, prop: 20, desc: "The microwave is not working", priority: "normal" },
    { id: 363, prop: 18, desc: "Ceiling Repair", priority: "normal" },
    { id: 362, prop: 23, desc: "Leak in the hose bib on the side of the house", priority: "normal" },
    { id: 361, prop: 67, desc: "Garage water damage - remove wet sheetrock and discard.", priority: "normal" },
    { id: 360, prop: 37, desc: "House Rental Permit Renewal", priority: "normal" },
    { id: 359, prop: 68, desc: "Need an HVAC combustion and smoke test", priority: "normal" },
    { id: 358, prop: 35, desc: "Pest Control", priority: "normal" },
    { id: 357, prop: 36, desc: "The front door is not closing properly.", priority: "normal" },
    { id: 356, prop: 6, desc: "Test Work Order", priority: "normal" },
    { id: 355, prop: 53, desc: "Remove the tree that fell into the neighbor's yard.", priority: "normal" },
    { id: 354, prop: 23, desc: "Replacement of the HVAC cross connects.", priority: "normal" },
    { id: 353, prop: 49, desc: "The dishwasher is leaking; door not closing properly.", priority: "normal" },
    { id: 352, prop: 56, desc: "Two electrical outlets are loose and don't hold plugs.", priority: "normal" },
    { id: 351, prop: 48, desc: "Gas remediation", priority: "normal" },
    { id: 350, prop: 48, desc: "Fix the roof", priority: "normal" },
    { id: 349, prop: 49, desc: "The refrigerator is leaking from the filter.", priority: "normal" },
    { id: 348, prop: 50, desc: "Gutter Cleaning", priority: "normal" },
    { id: 347, prop: 36, desc: "Sprinklers", priority: "normal" },
    { id: 346, prop: 49, desc: "Upstairs bath smell plus new exhaust fan", priority: "normal" },
    { id: 345, prop: 49, desc: "Kitchen faucet and plumbing", priority: "normal" },
    { id: 344, prop: 49, desc: "Fridge needs appliance repair to look at the filter", priority: "normal" },
    { id: 343, prop: 49, desc: "Installed 2 smoke detectors; need to send 2 CO detectors", priority: "normal" },
    { id: 342, prop: 49, desc: "The downstairs faucet needs weight", priority: "normal" },
    { id: 341, prop: 24, desc: "Order a new AC ($900)", priority: "normal" },
    { id: 340, prop: 27, desc: "Replace hot water stop valve", priority: "normal" },
    { id: 339, prop: 56, desc: "The outside outlet needs checking; not working", priority: "normal" },
    { id: 338, prop: 27, desc: "Replace the slow-leaking hot valve", priority: "normal" },
    { id: 337, prop: 49, desc: "Touch ups", priority: "normal" },
    { id: 336, prop: 44, desc: "Fix the walls in the closet", priority: "normal" },
    { id: 335, prop: 44, desc: "Fix gate", priority: "normal" },
    { id: 333, prop: 19, desc: "Outside light", priority: "normal" },
    { id: 332, prop: 24, desc: "Air conditioning", priority: "normal" },
    { id: 331, prop: 58, desc: "Replace storm door at back of house.", priority: "normal" },
    { id: 330, prop: 58, desc: "Replace garage door", priority: "normal" },
    { id: 329, prop: 58, desc: "Replace garage door", priority: "normal" },
    { id: 328, prop: 58, desc: "Cut down tree in backyard", priority: "normal" },
    { id: 327, prop: 58, desc: "Run exhaust to the exterior and repair the side window", priority: "normal" },
    { id: 326, prop: 36, desc: "Backflow testing", priority: "normal" },
    { id: 325, prop: 48, desc: "Air Conditioning", priority: "normal" },
    { id: 324, prop: 27, desc: "Need a new faucet. It is leaking", priority: "normal" },
    { id: 323, prop: 30, desc: "Basement damaged by leak from above; remediate water.", priority: "normal" },
    { id: 322, prop: 50, desc: "Gutter cleaning", priority: "normal" },
    { id: 321, prop: 51, desc: "Lawn Maintenance", priority: "normal" },
    { id: 320, prop: 11, desc: "Lawn Maintenance", priority: "normal" },
    { id: 319, prop: 48, desc: "Lights in the hallways are out", priority: "normal" },
    { id: 318, prop: 18, desc: "Roof Replacement", priority: "normal" },
    { id: 317, prop: 56, desc: "Petroleum smell outside", priority: "normal" },
    { id: 316, prop: 62, desc: "Asphalt and pavement works", priority: "normal" },
    { id: 315, prop: 6, desc: "Roof repair", priority: "normal" },
    { id: 314, prop: 50, desc: "The lights in the hallways are out.", priority: "normal" },
    { id: 313, prop: 50, desc: "Landscaper coming Monday to fix the sprinkler", priority: "normal" },
    { id: 312, prop: 56, desc: "Repair the fence", priority: "normal" },
    { id: 311, prop: 50, desc: "The lights in the hallways are out", priority: "normal" },
    { id: 310, prop: 53, desc: "Add fence to lock in the property all around", priority: "normal" },
    { id: 309, prop: 27, desc: "Replace 2-3 ceiling tiles in the basement.", priority: "normal" },
    { id: 308, prop: 27, desc: "Fence repair estimate - backyard on the left side", priority: "normal" },
    { id: 307, prop: 18, desc: "Fix the fence", priority: "normal" },
    { id: 306, prop: 51, desc: "Leak at the toilet", priority: "normal" },
    { id: 305, prop: 5, desc: "Repair the dryer vent cover", priority: "normal" },
    { id: 304, prop: 6, desc: "Repair the front stoop", priority: "normal" },
    { id: 303, prop: 35, desc: "Purchase fly traps", priority: "normal" },
    { id: 302, prop: 51, desc: "The downstairs toilet bowl is constantly running.", priority: "normal" },
    { id: 301, prop: 5, desc: "Dryer vent cleaning", priority: "normal" },
    { id: 300, prop: 5, desc: "Replace the shower body", priority: "normal" },
    { id: 299, prop: 52, desc: "Tenants have seen rats in the backyard under the shed.", priority: "normal" },
    { id: 298, prop: 49, desc: "Water leaking", priority: "normal" },
    { id: 297, prop: 35, desc: "There's a smell like an animal upstairs.", priority: "normal" },
    { id: 296, prop: 40, desc: "The bathroom light switch is broken; needs replacing.", priority: "normal" },
    { id: 295, prop: 40, desc: "The basement bathtub spout is loose.", priority: "normal" },
    { id: 294, prop: 56, desc: "Outlet above the sink has no power; electrician to fix.", priority: "normal" },
    { id: 293, prop: 56, desc: "Replacing garage ceiling lights with pull-down lights", priority: "normal" },
    { id: 292, prop: 56, desc: "Garage smoke detector replaced; replacing CO detector.", priority: "normal" },
    { id: 291, prop: 56, desc: "Repaired the bedroom TV outlet incl. new cover", priority: "normal" },
    { id: 290, prop: 56, desc: "Spackled and painted most of the interior.", priority: "normal" },
    { id: 289, prop: 56, desc: "Repair the closet door in one of the bedrooms", priority: "normal" },
    { id: 288, prop: 56, desc: "Repaired the bathroom door hinges.", priority: "normal" },
    { id: 287, prop: 56, desc: "Changed the locks (one-time setup fee)", priority: "normal" },
    { id: 286, prop: 18, desc: "Get rid of the raccoon in the attic", priority: "normal" },
    { id: 285, prop: 36, desc: "Heat is not working", priority: "normal" },
    { id: 284, prop: 56, desc: "Replace CO detectors", priority: "normal" },
    { id: 283, prop: 49, desc: "Deliver screen door", priority: "normal" },
    { id: 282, prop: 27, desc: "Sump Pump", priority: "normal" },
    { id: 281, prop: 48, desc: "Dehumidifier", priority: "normal" },
    { id: 280, prop: 48, desc: "Plumbing Test", priority: "normal" },
    { id: 279, prop: 18, desc: "Poison ivy coming over the fence from town property.", priority: "normal" },
    { id: 278, prop: 18, desc: "The vents are not pushing hot air the right way.", priority: "normal" },
    { id: 276, prop: 19, desc: "The refrigerator is leaking", priority: "normal" },
    { id: 275, prop: 19, desc: "The back door is leaking", priority: "normal" },
    { id: 274, prop: 48, desc: "Water utility - estimated meter reads issue.", priority: "normal" },
    { id: 273, prop: 55, desc: "Microwave replacement", priority: "normal" },
    { id: 272, prop: 30, desc: "The heating system is not working", priority: "normal" },
    { id: 271, prop: 48, desc: "Check the AC unit - loud noise, doesn't cool well.", priority: "normal" },
    { id: 270, prop: 48, desc: "Repair or replace the ceiling fan", priority: "normal" },
    { id: 269, prop: 27, desc: "Remove the tree that fell onto the pathway.", priority: "normal" },
    { id: 268, prop: 53, desc: "Get the Rental Permit", priority: "normal" },
    { id: 267, prop: 36, desc: "Water still leaking into toilets; get water-authority tablets.", priority: "normal" },
    { id: 266, prop: 11, desc: "Repair newly installed hood vent", priority: "normal" },
    { id: 265, prop: 52, desc: "Replace the front storm door", priority: "normal" },
    { id: 264, prop: 58, desc: "Electricity restoration", priority: "normal" },
    { id: 263, prop: 36, desc: "The basement door into the garage is sticking.", priority: "normal" },
    { id: 262, prop: 52, desc: "Old cesspool 'well' in front of the house is full of water.", priority: "high" },
    { id: 260, prop: 11, desc: "Fix the washing machine", priority: "normal" },
    { id: 259, prop: 37, desc: "Basement permit (smoke detectors + light); rental permit renewal.", priority: "normal" },
    { id: 258, prop: 48, desc: "There's a leak in the toilet", priority: "normal" },
    { id: 257, prop: 53, desc: "Bathroom renovation - plumbing estimate.", priority: "normal" },
    { id: 256, prop: 35, desc: "Water pressure drops to a trickle after a few minutes.", priority: "normal" },
    { id: 255, prop: 27, desc: "Leak in the basement - could be a waste line", priority: "normal" },
    { id: 254, prop: 52, desc: "Fix the upstairs vanity countertops", priority: "normal" },
    { id: 253, prop: 52, desc: "Fix the kitchen cabinet hinge", priority: "normal" },
    { id: 252, prop: 52, desc: "Get a new screen door", priority: "normal" },
    { id: 251, prop: 48, desc: "Getting the washer/dryer in the basement", priority: "normal" },
    { id: 250, prop: 36, desc: "New toilet seat cover - charge to Jonathan", priority: "normal" },
    { id: 249, prop: 51, desc: "Replace the bathroom faucet", priority: "normal" },
    { id: 248, prop: 5, desc: "Hot water handle is stripped; won't turn on/off", priority: "normal" },
    { id: 247, prop: 53, desc: "Water leaking through the garage ceiling from upstairs bath", priority: "normal" },
    { id: 245, prop: 49, desc: "Her window is not closing properly", priority: "normal" },
    { id: 244, prop: 37, desc: "Dryer vent is not installed properly", priority: "normal" },
    { id: 243, prop: 37, desc: "Mold behind the dryer; Disaster Clean Up assessing.", priority: "normal" },
    { id: 242, prop: 36, desc: "The thermostat is broken; won't go up to 80.", priority: "normal" },
    { id: 241, prop: 30, desc: "No electricity in the room by the basement.", priority: "normal" },
    { id: 240, prop: 51, desc: "The basement window is broken, letting in weather.", priority: "normal" },
    { id: 238, prop: 51, desc: "The upstairs bathroom sink leaks when running.", priority: "normal" },
    { id: 235, prop: 19, desc: "Need the floor fixed under the dishwasher", priority: "normal" },
    { id: 234, prop: 19, desc: "Microwave's door is not working", priority: "normal" },
    { id: 233, prop: 19, desc: "Circuit in the basement for the upstairs lights", priority: "normal" },
    { id: 232, prop: 27, desc: "No heat", priority: "normal" },
    { id: 231, prop: 6, desc: "Backsplash Installation", priority: "normal" },
    { id: 229, prop: 30, desc: "Flooded basement; a pipe burst - restoration engaged.", priority: "normal" },
    { id: 228, prop: 37, desc: "A burst pipe in the wall needs two people to repair.", priority: "normal" },
    { id: 227, prop: 27, desc: "She has no heat", priority: "normal" },
    { id: 226, prop: 19, desc: "The kitchen sink is not draining properly", priority: "normal" },
    { id: 225, prop: 41, desc: "Get full pricing for the blinds", priority: "normal" },
    { id: 224, prop: 19, desc: "Floor needs to be repaired.", priority: "normal" },
    { id: 223, prop: 19, desc: "The top shelf is tilting down and won't close.", priority: "normal" },
    { id: 222, prop: 37, desc: "Cesspool needs pumping; basement smells bad.", priority: "normal" },
    { id: 221, prop: 51, desc: "Oil installed but the heat won't turn on.", priority: "normal" },
    { id: 220, prop: 48, desc: "Outlet needs to be repaired", priority: "normal" },
    { id: 219, prop: 11, desc: "The spin cycle is not working", priority: "normal" },
    { id: 218, prop: 48, desc: "Radiators are clogged and need parts replaced.", priority: "normal" },
    { id: 214, prop: 40, desc: "Heat not working", priority: "low" },
    { id: 213, prop: 53, desc: "Heat is not working", priority: "normal" },
    { id: 212, prop: 11, desc: "Purchase of a new stove", priority: "normal" },
    { id: 211, prop: 51, desc: "The damaged-room closet door needs painting.", priority: "low" },
    { id: 210, prop: 30, desc: "Purchase a new stove", priority: "low" },
    { id: 209, prop: 36, desc: "Water company charged a lot - probable water leak.", priority: "normal" },
    { id: 208, prop: 48, desc: "Pest control for cockroaches in units 1, 2, and 3", priority: "normal" },
    { id: 207, prop: 41, desc: "The washer/dryer overfills with water when drying.", priority: "normal" },
    { id: 206, prop: 11, desc: "The refrigerator shelves keep falling off the door", priority: "normal" },
    { id: 205, prop: 11, desc: "Stove is broken", priority: "normal" },
    { id: 204, prop: 35, desc: "Fix upstairs access door", priority: "normal" },
    { id: 203, prop: 35, desc: "Have Dan look at the floor", priority: "normal" },
    { id: 202, prop: 30, desc: "Fix the ceiling.", priority: "normal" },
    { id: 201, prop: 41, desc: "Washer/dryer overfilling with water when drying", priority: "low" },
    { id: 200, prop: 30, desc: "Check the stove", priority: "high" },
    { id: 199, prop: 30, desc: "Check the stove", priority: "normal" },
    { id: 198, prop: 41, desc: "Washer/dryer overfilling with water when drying", priority: "normal" },
    { id: 197, prop: 36, desc: "Front toilet sounds like it's running", priority: "low" },
    { id: 196, prop: 52, desc: "Main floor thermostat not working; baseboards cold.", priority: "normal" },
    { id: 195, prop: 40, desc: "Fix the ceiling light in the bedroom", priority: "normal" },
    { id: 194, prop: 23, desc: "Garage Door Repair", priority: "low" },
    { id: 193, prop: 55, desc: "Water in the tub does not get hot.", priority: "low" },
    { id: 192, prop: 36, desc: "Basement toilet is leaking", priority: "low" },
    { id: 191, prop: 24, desc: "Order a new washer", priority: "low" },
    { id: 190, prop: 24, desc: "The repairman said it was not worth fixing", priority: "low" },
    { id: 189, prop: 40, desc: "Ceiling light needs to be replaced", priority: "low" },
    { id: 188, prop: 40, desc: "Light bulb hanging down in one of the bedrooms", priority: "low" },
    { id: 187, prop: 40, desc: "The toilet flusher is broken", priority: "low" },
    { id: 186, prop: 55, desc: "House cleaning", priority: "low" },
    { id: 185, prop: 53, desc: "HVAC service needed - system won't turn on.", priority: "low" },
    { id: 184, prop: 6, desc: "Backsplash & countertops", priority: "low" },
    { id: 183, prop: 55, desc: "House cleaning before move in", priority: "low" },
    { id: 182, prop: 24, desc: "Washing machine is stuck, full and closed.", priority: "low" },
    { id: 181, prop: 53, desc: "Basement renovation", priority: "low" },
    { id: 180, prop: 51, desc: "Fix a leaking pipe", priority: "low" },
    { id: 179, prop: 44, desc: "Shower head in the main bathroom drips", priority: "low" },
    { id: 178, prop: 49, desc: "Basement repair from water damage", priority: "low" },
    { id: 177, prop: 5, desc: "Replace kitchen sheetrock from the HVAC installation.", priority: "low" },
    { id: 175, prop: 48, desc: "New thermostat installation", priority: "low" },
    { id: 174, prop: 48, desc: "Range hood fan on top of the stove is not working", priority: "low" },
    { id: 173, prop: 48, desc: "Dishwasher is leaking", priority: "low" },
    { id: 172, prop: 48, desc: "Multiple broken risers on the steps, floor 2 to 3", priority: "low" },
    { id: 171, prop: 30, desc: "Heater is not working", priority: "low" },
    { id: 170, prop: 36, desc: "Sprinkler Winterization", priority: "low" },
    { id: 169, prop: 6, desc: "Sprinkler Winterization", priority: "low" },
    { id: 168, prop: 24, desc: "Sprinkler Winterization", priority: "low" },
    { id: 167, prop: 19, desc: "Sprinkler Winterization", priority: "low" },
    { id: 166, prop: 5, desc: "Take the sheetrock down", priority: "low" },
    { id: 165, prop: 51, desc: "Needs the door fixed.", priority: "low" },
    { id: 164, prop: 45, desc: "Garage door is not working again.", priority: "low" },
    { id: 163, prop: 36, desc: "Oven dials not working; Choice Home Warranty claim.", priority: "low" },
    { id: 162, prop: 49, desc: "Dishwasher installed too close to the wall; leaking.", priority: "low" },
    { id: 161, prop: 40, desc: "Plumbing for the kitchen sink is disconnected.", priority: "high" },
    { id: 160, prop: 50, desc: "Termite preventative treatment - sign up to KnockOut", priority: "low" },
    { id: 159, prop: 18, desc: "Heat not coming through the vents though the furnace runs.", priority: "low" },
    { id: 158, prop: 6, desc: "Countertops and backsplash replacement", priority: "low" },
    { id: 157, prop: 53, desc: "Generator Maintenance", priority: "low" },
    { id: 156, prop: 44, desc: "Remove the tree that fell during the storm.", priority: "normal" },
    { id: 155, prop: 41, desc: "Fix blinds - not opening with the remote", priority: "low" },
    { id: 154, prop: 49, desc: "Dishwasher Replacement", priority: "normal" },
    { id: 153, prop: 41, desc: "Pest Control - flies found in both bedrooms", priority: "normal" },
    { id: 152, prop: 49, desc: "Dishwasher is leaking", priority: "normal" },
    { id: 151, prop: 49, desc: "The garage door opener is broken (1/2 HP)", priority: "normal" },
    { id: 150, prop: 49, desc: "Upstairs window doesn't open properly", priority: "normal" },
    { id: 149, prop: 49, desc: "Side door needs to be adjusted", priority: "normal" },
    { id: 148, prop: 49, desc: "Basement light fixture needs replacing; cover missing.", priority: "normal" },
    { id: 147, prop: 49, desc: "One smoke detector needs to be replaced", priority: "normal" },
    { id: 146, prop: 51, desc: "Roof flashing detached along the eaves", priority: "normal" },
    { id: 145, prop: 44, desc: "The lights are out in the loft", priority: "normal" },
    { id: 144, prop: 23, desc: "See if Ross wants the sprinklers winterized", priority: "normal" },
    { id: 143, prop: 23, desc: "Fix the dripping faucet", priority: "normal" },
    { id: 142, prop: 23, desc: "Send pest control for the bee infestation", priority: "normal" },
    { id: 141, prop: 36, desc: "Refrigerator temp rising; Choice Home Warranty claim.", priority: "normal" },
    { id: 140, prop: 53, desc: "Contact Glen Cove for bulk furniture pickup", priority: "normal" },
    { id: 139, prop: 41, desc: "Sink is draining slow", priority: "normal" },
    { id: 138, prop: 45, desc: "Replace a light fixture cover in the downstairs bathroom.", priority: "normal" },
    { id: 137, prop: 20, desc: "Door repair - hinges broken, door not closing.", priority: "high" },
    { id: 136, prop: 52, desc: "Upstairs shower diverter valve not working; send a plumber.", priority: "high" },
    { id: 134, prop: 49, desc: "Pest Control", priority: "normal" },
    { id: 133, prop: 36, desc: "The oven isn't closing all the way - CHW claim.", priority: "normal" },
    { id: 132, prop: 40, desc: "Fix the water connection to the washing machine", priority: "normal" },
    { id: 131, prop: 40, desc: "Fixing the lights in the basement", priority: "normal" },
    { id: 130, prop: 35, desc: "Saddle needs repair between the bedroom and living room", priority: "normal" },
    { id: 129, prop: 50, desc: "House Cleaning", priority: "normal" },
    { id: 128, prop: 44, desc: "Lawn", priority: "normal" },
    { id: 127, prop: 48, desc: "Lead Testing", priority: "normal" },
    { id: 126, prop: 49, desc: "Purchase shower doors, head/handle, mirror, cabinet.", priority: "normal" },
    { id: 125, prop: 50, desc: "Junk Removal", priority: "normal" },
    { id: 124, prop: 36, desc: "Issue with the lights", priority: "normal" },
    { id: 123, prop: 5, desc: "A/C unit replacement", priority: "normal" },
    { id: 122, prop: 44, desc: "Retaining wall and brick work", priority: "normal" },
    { id: 121, prop: 49, desc: "Measure and purchase window screens", priority: "normal" },
    { id: 120, prop: 50, desc: "Painting of the house", priority: "normal" },
    { id: 119, prop: 36, desc: "Check the refrigerator", priority: "normal" },
    { id: 118, prop: 53, desc: "Garage ceiling leaking from the upstairs bathroom pipe.", priority: "normal" },
    { id: 117, prop: 53, desc: "Mold Remediation", priority: "high" },
    { id: 116, prop: 27, desc: "Washing machine pipe leaking", priority: "normal" },
    { id: 115, prop: 36, desc: "Replace door stop for the first-floor bedroom door", priority: "normal" },
    { id: 114, prop: 35, desc: "Pest Control: Bees", priority: "normal" },
    { id: 113, prop: 35, desc: "Pest Control: Flies", priority: "normal" },
    { id: 112, prop: 48, desc: "Lawn maintenance - weed removal and grass cutting", priority: "normal" },
    { id: 111, prop: 52, desc: "Removal of the furniture in the house", priority: "normal" },
    { id: 110, prop: 48, desc: "Kitchen sink leak, possibly affecting the first floor", priority: "high" },
    { id: 109, prop: 36, desc: "Replace broken light under the cabinet", priority: "normal" },
    { id: 108, prop: 51, desc: "Pad under the sink is completely saturated with water", priority: "normal" },
    { id: 107, prop: 35, desc: "Fix floors", priority: "normal" },
    { id: 106, prop: 19, desc: "Replace smoke detectors", priority: "normal" },
    { id: 104, prop: 48, desc: "Purchase and install a cork board", priority: "normal" },
    { id: 103, prop: 41, desc: "Outlet now working", priority: "normal" },
    { id: 102, prop: 36, desc: "Vent cleaning", priority: "normal" },
    { id: 101, prop: 49, desc: "Mold Remediation", priority: "normal" },
    { id: 100, prop: 30, desc: "Leak in the ceiling downstairs.", priority: "normal" },
    { id: 99, prop: 20, desc: "Leak in the ceiling.", priority: "normal" },
    { id: 98, prop: 48, desc: "Find a landscaping company for the front of the property.", priority: "normal" },
    { id: 97, prop: 48, desc: "Find a cleaner for the common areas (bi-weekly).", priority: "normal" },
    { id: 96, prop: 5, desc: "A/C not working; outdoor unit not working.", priority: "normal" },
    { id: 95, prop: 41, desc: "Move furniture to temporary storage", priority: "normal" },
    { id: 94, prop: 41, desc: "Deliver to Hackensack (furniture & boxes)", priority: "normal" },
    { id: 93, prop: 41, desc: "Cleaning (incl. discarding remaining items)", priority: "normal" },
    { id: 92, prop: 48, desc: "Repair work - mold remediation; sheetrock replaced.", priority: "normal" },
    { id: 90, prop: 6, desc: "Opening on the roof needs to be closed", priority: "normal" },
    { id: 89, prop: 19, desc: "Fix the top step inside", priority: "normal" },
    { id: 88, prop: 27, desc: "Snaked basement toilet; tested ejector pump and sewer.", priority: "normal" },
    { id: 87, prop: 20, desc: "Fix appliances - oven and refrigerator", priority: "normal" },
    { id: 86, prop: 30, desc: "Plumbing issue", priority: "normal" },
    { id: 85, prop: 30, desc: "Heating downstairs not working", priority: "normal" },
    { id: 84, prop: 6, desc: "Raccoon trapping", priority: "normal" },
    { id: 83, prop: 5, desc: "Handyman works", priority: "normal" },
    { id: 82, prop: 20, desc: "Handyman works", priority: "normal" },
    { id: 81, prop: 20, desc: "Fix heater - no heat in the house", priority: "normal" },
    { id: 80, prop: 30, desc: "Fix the heating upstairs.", priority: "normal" },
    { id: 79, prop: 30, desc: "Shower had no hot water; replaced valve and head.", priority: "normal" },
    { id: 78, prop: 35, desc: "Bathroom remediation per proposal (containment, demo, sanitize).", priority: "normal" },
    { id: 77, prop: 35, desc: "Bathroom rebuild per proposal (insulation, tile, grout).", priority: "normal" },
    { id: 76, prop: 11, desc: "Heating Tune-up", priority: "normal" },
    { id: 75, prop: 6, desc: "Heating Tune-up", priority: "normal" },
    { id: 74, prop: 19, desc: "Heating Tune-up", priority: "normal" },
    { id: 73, prop: 5, desc: "Heating Tune-up", priority: "normal" },
    { id: 72, prop: 35, desc: "Handyman Work", priority: "normal" },
    { id: 71, prop: 30, desc: "Toilet seat replacement and handyman works", priority: "normal" },
    { id: 70, prop: 19, desc: "Two new thermostats and installation", priority: "normal" },
    { id: 69, prop: 27, desc: "Ceiling crack, shower door fix, caulk satellite dish.", priority: "normal" },
    { id: 68, prop: 18, desc: "Cut a hole / add a door to reach the HVAC unit", priority: "normal" },
    { id: 67, prop: 24, desc: "Repaired leak from main shut-off valve; new ball valve.", priority: "normal" },
    { id: 66, prop: 18, desc: "HVAC heating problem", priority: "normal" },
    { id: 65, prop: 6, desc: "Problem with the toilet at the back of the house.", priority: "normal" },
    { id: 64, prop: 19, desc: "Sprinkler blow out for winter", priority: "normal" },
    { id: 63, prop: 24, desc: "Sprinkler needs to be blown out for the winter.", priority: "normal" },
    { id: 62, prop: 6, desc: "Sprinkler needs to be blown out for the winter.", priority: "normal" },
    { id: 61, prop: 6, desc: "Problem with the toilet at the back of the house.", priority: "normal" },
    { id: 60, prop: 30, desc: "Hot water in the bathroom is not working.", priority: "normal" },
    { id: 58, prop: 30, desc: "Handyman works", priority: "normal" },
    { id: 57, prop: 30, desc: "Hook up the dishwasher; re-run the disconnected pipe.", priority: "normal" },
    { id: 56, prop: 30, desc: "Dishwasher wires not connected correctly (extension cord).", priority: "normal" },
    { id: 55, prop: 30, desc: "House Cleaning.", priority: "normal" },
    { id: 54, prop: 27, desc: "Boiler service - replaced filter/nozzle, tested zones.", priority: "normal" },
    { id: 53, prop: 24, desc: "Dishwasher wasn't working.", priority: "normal" },
    { id: 52, prop: 18, desc: "Roofing repair", priority: "normal" },
    { id: 51, prop: 27, desc: "Roof - clear needles, tar skylight/flue, replace ridge caps.", priority: "normal" },
    { id: 50, prop: 27, desc: "Basement toilet not draining; replaced ejector pump float.", priority: "normal" },
    { id: 49, prop: 27, desc: "Ceiling fan not working - fixed splices, swapped bulb.", priority: "normal" },
    { id: 48, prop: 27, desc: "Basement floor, basement shower head, touch-up paint", priority: "normal" },
    { id: 47, prop: 18, desc: "Power wash the fence; clean the gutters", priority: "normal" },
    { id: 46, prop: 27, desc: "Lawn Care Service", priority: "normal" },
    { id: 45, prop: 27, desc: "Lawn Care Service", priority: "normal" },
    { id: 44, prop: 6, desc: "A kitchen fuse keeps tripping; tenant resets it.", priority: "normal" },
    { id: 43, prop: 18, desc: "Install the garage door opener ($413 incl. install)", priority: "normal" },
    { id: 42, prop: 18, desc: "Downstairs sink not draining properly", priority: "normal" },
    { id: 41, prop: 18, desc: "Fix Tub", priority: "normal" },
    { id: 38, prop: 18, desc: "Fix leaking upstairs sink, water pressure, hot water temp.", priority: "normal" },
    { id: 37, prop: 18, desc: "Fix hole by front door, caulk, shower doors, dryer vent.", priority: "normal" },
    { id: 36, prop: 6, desc: "Pool Cleaning Service", priority: "normal" },
    { id: 34, prop: 18, desc: "Some outlets not working and outside lights", priority: "normal" },
    { id: 31, prop: 20, desc: "Kitchen faucet leaking; toilet leaks from the supply hose.", priority: "normal" },
    { id: 29, prop: 18, desc: "House Cleaning", priority: "normal" },
    { id: 28, prop: 23, desc: "Toilet lid replacement", priority: "normal" },
    { id: 27, prop: 27, desc: "Steps, front post, fix siding, clean gutters, spackling", priority: "normal" },
    { id: 23, prop: 5, desc: "Leaking under the sink in the primary bathroom.", priority: "normal" },
    { id: 22, prop: 19, desc: "Plumbing - flushing the toilet backs up to the shower.", priority: "high" },
    { id: 21, prop: 19, desc: "The fence needed is ~10ft by 24ft.", priority: "normal" },
    { id: 19, prop: 20, desc: "House Cleaning for Listing", priority: "normal" },
    { id: 16, prop: 6, desc: "Water in the basement, flooding.", priority: "high" },
    { id: 15, prop: 19, desc: "Leaking in the sprinklers", priority: "normal" },
    { id: 13, prop: 5, desc: "Oven - warranty appointment for the rubber edging.", priority: "normal" },
    { id: 11, prop: 6, desc: "Air conditioning unit leaking", priority: "high" },
    { id: 10, prop: 6, desc: "Backyard fence broken; fix gate latch, cut stump, check roof.", priority: "high" },
    { id: 9, prop: 18, desc: "Pest extermination - rats in the garage (PestShare).", priority: "normal" },
    { id: 6, prop: 6, desc: "Front storm door won't close; recommend replacement.", priority: "normal" },
    { id: 4, prop: 5, desc: "Front door key not working; handle needed replacing.", priority: "normal" },
    { id: 3, prop: 5, desc: "Leaks in both bathrooms; replace tub/shower valves.", priority: "low" },
    { id: 1, prop: 6, desc: "Stove breaker tripping; loose wire reconnected.", priority: "normal" },
  ],
};
